import PageShell from "@/components/PageShell";
import Collapsible from "@/components/Collapsible";
const works=[
{title:"ESG & Sustainability Implementation",overview:"Supported organizations in translating sustainability ambitions into practical implementation systems through governance structures, implementation roadmaps, reporting frameworks, accountability mechanisms, and performance measurement approaches.",items:["Developed ESG implementation roadmaps and organizational action plans","Conducted materiality and sustainability prioritization exercises","Designed governance structures and accountability frameworks","Built ESG scorecards, KPI libraries, dashboards, and reporting structures","Supported alignment with GRI, IFRS S1 and S2, SASB, CSRD, and TCFD","Developed practical implementation tools, templates, and process documentation"]},
{title:"Program, Project & Operational Management",overview:"Coordinated and supported complex multi-stakeholder initiatives by strengthening operational systems, project governance, reporting structures, stakeholder engagement, and implementation planning.",items:["Managed cross-functional program operations involving diverse international stakeholders","Coordinated events, logistics, timelines, and operational activities","Designed project tracking systems and reporting processes","Improved workflows through structured planning and documentation","Developed operating procedures, communication workflows, and implementation plans","Supported continuous improvement through monitoring and stakeholder feedback"]},
{title:"Climate, Infrastructure & Systems Innovation",overview:"Contributed to sustainability initiatives focused on climate resilience, infrastructure performance, operational efficiency, and long-term decision-making through systems thinking and emerging technologies.",items:["Developed AI-enabled concepts for infrastructure resilience and maintenance planning","Connected sustainability priorities with operational performance and delivery","Explored data and technology applications for infrastructure decision-making","Supported climate resilience and systems innovation initiatives","Developed implementation frameworks for sustainability-focused operational improvements","Integrated sustainability considerations into infrastructure and organizational planning"]},
{title:"Data, Reporting & Decision Support",overview:"Designed reporting systems, performance measurement approaches, and decision-support tools that strengthened sustainability reporting, data quality, monitoring, and organizational accountability.",items:["Developed ESG performance dashboards and reporting templates","Built KPI frameworks and sustainability measurement systems","Designed data collection and validation processes","Standardized indicators to improve reporting consistency","Supported environmental and sustainability performance monitoring","Developed decision-support resources for governance and management reporting"]}
];
export default function SelectedWork(){return <PageShell eyebrow="Selected Work" title="Representative work that demonstrates execution" description="Selected examples of implementation, advisory, and operational work completed across sustainability, climate, governance, reporting, systems innovation, and organizational performance—presented without disclosing confidential client information."><section className="section"><div className="container work-list">{works.map((w,i)=><article className="work-card" key={w.title}><div><span className="tag">Selected Work {String(i+1).padStart(2,"0")}</span><h2>{w.title}</h2><p>{w.overview}</p></div><div><h3>Representative Work</h3><Collapsible label="See details +" openLabel="Show less"><ul>{w.items.map(x=><li key={x}>{x}</li>)}</ul></Collapsible></div></article>)}</div></section></PageShell>}
