import type { Metadata } from "next";
import PageShell from "@/components/PageShell";
import Collapsible from "@/components/Collapsible";
import Reveal from "@/components/Reveal";
import { Leaf, Network, Building2, BarChart3 } from "lucide-react";
export const metadata: Metadata = { title: "Our Work", description: "Implementation, advisory, and operational work across sustainability, climate, governance, and reporting." };
const works=[
{icon:Leaf,image:"https://images.pexels.com/photos/7681091/pexels-photo-7681091.jpeg?auto=compress&cs=tinysrgb&w=800",title:"ESG & Sustainability Implementation",impact:"Stronger governance, implementation readiness, and reporting consistency",summary:"Governance structures, KPI frameworks, and reporting systems that turned ESG ambition into practice.",overview:"Supported organizations in translating sustainability ambitions into practical implementation systems through governance structures, implementation roadmaps, reporting frameworks, accountability mechanisms, and performance measurement approaches.",items:["Developed ESG implementation roadmaps and organizational action plans","Conducted materiality and sustainability prioritization exercises","Designed governance structures and accountability frameworks","Built ESG scorecards, KPI libraries, dashboards, and reporting structures","Supported alignment with GRI, IFRS S1 and S2, SASB, CSRD, and TCFD","Developed practical implementation tools, templates, and process documentation"]},
{icon:Network,image:"https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=800",title:"Program, Project & Operational Management",impact:"Improved coordination, execution visibility, and delivery discipline",summary:"Cross-functional program coordination, workflow design, and delivery discipline for complex initiatives.",overview:"Coordinated and supported complex multi-stakeholder initiatives by strengthening operational systems, project governance, reporting structures, stakeholder engagement, and implementation planning.",items:["Managed cross-functional program operations involving diverse international stakeholders","Coordinated events, logistics, timelines, and operational activities","Designed project tracking systems and reporting processes","Improved workflows through structured planning and documentation","Developed operating procedures, communication workflows, and implementation plans","Supported continuous improvement through monitoring and stakeholder feedback"]},
{icon:Building2,image:"https://images.pexels.com/photos/35158337/pexels-photo-35158337.jpeg?auto=compress&cs=tinysrgb&w=800",title:"Climate, Infrastructure & Systems Innovation",impact:"Stronger resilience, systems visibility, and implementation planning",summary:"Climate resilience and AI-enabled infrastructure concepts grounded in systems thinking.",overview:"Contributed to sustainability initiatives focused on climate resilience, infrastructure performance, operational efficiency, and long-term decision-making through systems thinking and emerging technologies.",items:["Developed AI-enabled concepts for infrastructure resilience and maintenance planning","Connected sustainability priorities with operational performance and delivery","Explored data and technology applications for infrastructure decision-making","Supported climate resilience and systems innovation initiatives","Developed implementation frameworks for sustainability-focused operational improvements","Integrated sustainability considerations into infrastructure and organizational planning"]},
{icon:BarChart3,image:"https://images.pexels.com/photos/577210/pexels-photo-577210.jpeg?auto=compress&cs=tinysrgb&w=800",title:"Data, Reporting & Decision Support",impact:"Better data quality, performance measurement, and decision support",summary:"Dashboards, KPI libraries, and decision-support tools that strengthened reporting accountability.",overview:"Designed reporting systems, performance measurement approaches, and decision-support tools that strengthened sustainability reporting, data quality, monitoring, and organizational accountability.",items:["Developed ESG performance dashboards and reporting templates","Built KPI frameworks and sustainability measurement systems","Designed data collection and validation processes","Standardized indicators to improve reporting consistency","Supported environmental and sustainability performance monitoring","Developed decision-support resources for governance and management reporting"]}
];
export default function SelectedWork(){return <PageShell eyebrow="Our Work" title="Execution across sustainability, climate, and governance" description="Implementation, advisory, and operational work completed across sustainability, climate, governance, reporting, systems innovation, and organizational performance, presented without disclosing confidential client information."><Reveal><section className="section"><div className="container work-list">{works.map((w,i)=>{const I=w.icon;return <article className="work-card work-card--media" key={w.title}><div className="work-card-media"><img src={w.image} alt="" loading="lazy"/><span className="work-card-badge"><I size={18}/></span></div><div className="work-card-body"><span className="tag">Our Work {String(i+1).padStart(2,"0")}</span><h2 style={{marginTop:8}}>{w.title}</h2><p className="lead" style={{fontSize:16,marginTop:8}}>{w.summary}</p><p style={{fontSize:14,fontWeight:600,color:"var(--terracotta)",marginTop:10}}>Impact: {w.impact}</p><Collapsible label="See full details +" openLabel="Show less"><p style={{marginTop:0}}>{w.overview}</p><h3 style={{fontSize:16,marginTop:20}}>Representative Work</h3><ul>{w.items.map(x=><li key={x}>{x}</li>)}</ul></Collapsible></div></article>})}</div></section></Reveal></PageShell>}
