import type { Metadata } from "next";
import PageShell from "@/components/PageShell";
import Collapsible from "@/components/Collapsible";
import Reveal from "@/components/Reveal";
import { Leaf, Network, Building2, BarChart3 } from "lucide-react";
export const metadata: Metadata = { title: "Our Work", description: "Implementation, advisory, and operational work across sustainability governance, program management, climate resilience, and data and reporting." };
const works=[
{icon:Leaf,image:"https://images.pexels.com/photos/7681091/pexels-photo-7681091.jpeg?auto=compress&cs=tinysrgb&w=800",title:"ESG Governance & Sustainability Implementation",summary:"Governance structures, a working roadmap, and reporting discipline that turned sustainability ambition into practice.",outcome:"Stronger governance, clearer ownership, and reporting that held up quarter after quarter.",before:"Sustainability existed mostly as intention, an ambition raised in meetings with no owner, no roadmap, and no way to show progress when customers or lenders asked.",after:"A defined governance structure, a materiality-driven roadmap, and reporting aligned with recognized frameworks including GRI, IFRS S1 and S2, SASB, CSRD, and TCFD, giving leadership a system they could run on their own."},
{icon:Network,image:"https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=800",title:"Program, Project & Operational Management",summary:"Coordinated delivery across complex, multi-stakeholder initiatives so priorities did not stall after the planning stage.",outcome:"Coordinated delivery, real visibility, and initiatives that stayed on schedule instead of losing momentum.",before:"Sustainability initiatives were scattered across teams and stakeholders, with no shared tracking system and no single view of what was actually getting done.",after:"Structured workplans, defined ownership, and reporting processes gave leadership real visibility into delivery, and gave the team a repeatable way to keep initiatives moving on their own."},
{icon:Building2,image:"https://images.pexels.com/photos/35158337/pexels-photo-35158337.jpeg?auto=compress&cs=tinysrgb&w=800",title:"Climate Risk & Resilience Planning",summary:"Translated climate and environmental exposure into a resilience plan the operations team could actually execute.",outcome:"A clear-eyed view of exposure and a resilience plan operations could run with.",before:"Climate risk was discussed in the abstract, raised in strategy conversations but never translated into anything the operations team could act on.",after:"A practical resilience plan grounded in the business's actual exposure, monitoring in place, and a plan operations could execute rather than file away."},
{icon:BarChart3,image:"https://images.pexels.com/photos/577210/pexels-photo-577210.jpeg?auto=compress&cs=tinysrgb&w=800",title:"Data, Reporting & Decision Support",summary:"Built the measurement systems that turned scattered sustainability activity into evidence leadership could actually use.",outcome:"Consistent indicators and dashboards leadership actually opened, not just filed.",before:"Sustainability data lived in disconnected spreadsheets and one-off reports, inconsistent from quarter to quarter and too scattered to act on.",after:"Standardized KPIs, validated data collection, and dashboards that turned activity into decisions leadership could stand behind."}
];
export default function SelectedWork(){return <PageShell eyebrow="Our Work" title="Implementation, advisory, and operational work completed across sustainability governance, program management, climate resilience, and data and reporting."><Reveal><section className="section"><div className="container work-list">{works.map(w=>{const I=w.icon;return <article className="work-card work-card--media" key={w.title}><div className="work-card-media"><img src={w.image} alt="" loading="lazy"/><span className="work-card-badge"><I size={18}/></span></div><div className="work-card-body"><h2>{w.title}</h2><p className="lead" style={{fontSize:16,marginTop:8}}>{w.summary}</p><p style={{fontSize:14,fontWeight:600,color:"var(--terracotta)",marginTop:10}}>Outcome: {w.outcome}</p><Collapsible label="See the full story +" openLabel="Show less"><p style={{marginTop:0}}><b>Where it started: </b>{w.before}</p><p style={{marginTop:14}}><b>Where it landed: </b>{w.after}</p></Collapsible></div></article>})}</div></section></Reveal></PageShell>}
