import type { Metadata } from "next";
import PageShell from "@/components/PageShell";
import Collapsible from "@/components/Collapsible";
import Reveal from "@/components/Reveal";
import { Leaf, Building2, Target, BarChart3, Cog, ClipboardCheck } from "lucide-react";
export const metadata: Metadata = { title: "Services", description: "Connected capabilities for sustainability implementation: readiness and strategy, implementation and program management, operational systems, measurement and data, climate impact and responsible sourcing, and credible reporting." };
const services=[
[Leaf,"Sustainability and Climate Strategy","We assess where sustainability efforts stand today and translate ambition, customer expectations, and market pressure into clear priorities and an achievable implementation roadmap."],
[Target,"Implementation and Program Management","We turn the roadmap into action through structured project and program plans, defined ownership, milestones, and coordinated delivery, so priorities do not stall after the planning stage."],
[Cog,"Operational Systems and Process Improvement","We build the everyday workflows, procedures, and accountability structures that embed sustainability into how the business actually operates."],
[BarChart3,"Data, Measurement, and Reporting","We develop key performance indicators, build dashboards, and design data collection processes that turn scattered information into evidence leadership can act on."],
[Building2,"Climate Impact and Resilience","We measure climate and environmental performance and help the business plan for resilience where it matters most to its operations."],
[ClipboardCheck,"Responsible Sourcing and Supply Chain","We help businesses respond to customer and lender sustainability requirements and strengthen sourcing and supply chain practices."]
];
export default function Services(){return <PageShell eyebrow="Services" title="Capabilities that turn sustainability goals into practical systems" description="Calden Terre combines sustainability expertise with hands-on implementation, operational systems, measurement, and credible communication, presented as one connected approach for established small and growing businesses working to move from intention to practical progress."><Reveal><section className="section"><div className="container grid-3">{services.map(([Icon,t,d])=>{const I=Icon as typeof Leaf;return <article className="card" key={String(t)}><div className="icon-badge"><I size={22}/></div><h3>{String(t)}</h3><Collapsible><p>{String(d)}</p></Collapsible></article>})}</div>
<div className="offering-block" id="finance"><div className="eyebrow">A Separate Offering, For Financial Institutions</div><h2 style={{marginTop:10}}>Sustainable Lending &amp; Investment Advisory</h2><p className="lead" style={{fontSize:16,marginTop:12,maxWidth:760}}>This is a distinct offering, built for banks, CDFIs, and other financial institutions rather than for growing businesses directly. We help these institutions build the ESG due diligence frameworks, risk scorecards, and climate disclosure systems they need to lend, invest, and report with confidence.</p><div style={{marginTop:8}}><Building2 size={20} style={{verticalAlign:"middle",marginRight:8,color:"var(--terracotta)"}}/><span style={{fontSize:13,color:"var(--body)"}}>See <a href="/#who-we-serve" style={{color:"var(--terracotta)",fontWeight:600}}>Who We Serve</a> for how this fits alongside our institutional partnership programs.</span></div></div>
</section></Reveal></PageShell>}
