import type { Metadata } from "next";
import PageShell from "@/components/PageShell";
import Collapsible from "@/components/Collapsible";
import Reveal from "@/components/Reveal";
import { Search, Compass, Rocket, TrendingUp, ShieldCheck, Landmark } from "lucide-react";
export const metadata: Metadata = { title: "Services", description: "Five services that follow the Calden Terre Impact Framework: readiness assessment, roadmap and strategy, implementation and systems build, ongoing advisory, and credibility and readiness support, plus a separate Sustainable Lending & Investment Advisory offering for financial institutions." };
const services=[
[Search,"Discover","Sustainability Readiness Assessment","A structured first look at where your sustainability efforts stand today, what your customers, lenders, or investors are actually asking for, and two or three practical actions you can start on right away."],
[Compass,"Strategize","Roadmap & Strategy","We turn scattered ambition into a scoped, sequenced plan sized to what your business can realistically resource, with clear ownership and a small number of specific, achievable goals."],
[Rocket,"Implement","Implementation & Systems Build","The core of our work. We build the everyday workflows, procedures, supplier and data systems, and accountability structures that carry sustainability from plan into daily operations."],
[TrendingUp,"Measure & Optimize","Ongoing Advisory & Accountability","Continued guidance once implementation is underway: tracking progress, troubleshooting what isn't working, and keeping momentum and accountability in place month over month."],
[ShieldCheck,"Sustain","Credibility & Readiness Support","Support responding to lender ESG questionnaires, customer sustainability requirements, and RFPs, and preparing for third-party certification if and when you choose to pursue one."]
];
export default function Services(){return <PageShell eyebrow="Services" title="Five services that follow the same path as our six-stage framework, meeting your business at whatever stage of implementation it's in today."><Reveal><section className="section"><div className="container grid-3">{services.map(([Icon,stage,t,d])=>{const I=Icon as typeof Search;return <article className="card" key={String(t)}><div className="icon-badge"><I size={22}/></div><span style={{display:"block",fontSize:11,fontWeight:700,letterSpacing:".08em",textTransform:"uppercase",color:"var(--terracotta)",marginBottom:8}}>Framework: {String(stage)}</span><h3>{String(t)}</h3><Collapsible><p>{String(d)}</p></Collapsible></article>})}
<article className="card" id="finance"><div className="icon-badge"><Landmark size={22}/></div><span style={{display:"block",fontSize:11,fontWeight:700,letterSpacing:".08em",textTransform:"uppercase",color:"var(--terracotta)",marginBottom:8}}>For Financial Institutions</span><h3>Sustainable Lending &amp; Investment Advisory</h3><Collapsible><p>A distinct offering built for banks, CDFIs, and other financial institutions rather than for growing businesses directly. We help these institutions build the ESG due diligence frameworks, risk scorecards, and climate disclosure systems they need to lend, invest, and report with confidence.</p></Collapsible></article>
</div><p style={{marginTop:36}}><a href="/framework" style={{color:"var(--terracotta)",fontWeight:600,fontSize:14}}>See the full six-stage Calden Terre Impact Framework →</a></p>
</section></Reveal></PageShell>}
