import type { Metadata } from "next";
import PageShell from "@/components/PageShell";
import Reveal from "@/components/Reveal";
import { MessageSquare, Mail } from "lucide-react";
export const metadata: Metadata = { title: "Contact", description: "Tell us about your organization, priorities, and implementation needs, and we'll use your message to understand the best next step." };

const organizationTypes=["Established Small Business","Growing Business","CDFI or Community Lender","Business-Support Organization","Nonprofit or Foundation","Other"];
const supportAreas=["Sustainability Readiness Assessment","Sustainability Implementation Roadmap","Operational Systems and Process Improvement","Program or Project Implementation","KPI Development and Performance Measurement","Sustainability Data and Dashboards","Impact Measurement and Reporting","Responsible Sourcing and Supply-Chain Support","Climate and Resource Performance","Sustainability Communication","Cohort Training or Sponsored Business Program","Other"];

export default function Contact(){return <PageShell eyebrow="Start a Project" title="Tell us about your organization, priorities, and implementation needs. We will use your message to understand the best next step."><Reveal><section className="section"><div className="container contact-grid"><div><div className="icon-badge"><MessageSquare size={22}/></div><h2>Start a project conversation</h2><p className="lead" style={{fontSize:18,display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}><Mail size={16}/> <span>For direct inquiries, email <a style={{color:"var(--terracotta)",fontWeight:600}} href="mailto:info@caldenterre.com">info@caldenterre.com</a>.</span></p></div><form className="contact-form" action="mailto:info@caldenterre.com" method="post" encType="text/plain"><div className="field"><label htmlFor="name">Name</label><input id="name" name="name" required/></div><div className="field"><label htmlFor="email">Email</label><input id="email" type="email" name="email" required/></div><div className="field"><label htmlFor="organization">Organization</label><input id="organization" name="organization"/></div><div className="field"><label htmlFor="organizationType">Organization Type</label><select id="organizationType" name="organizationType" defaultValue="">
  <option value="" disabled>Select one</option>
  {organizationTypes.map(o=><option key={o} value={o}>{o}</option>)}
</select></div><div className="field"><label>Areas of Support</label><div className="support-pills">{supportAreas.map((a,i)=><span key={a}><input type="checkbox" id={`support-${i}`} name="support" value={a}/><label htmlFor={`support-${i}`}>{a}</label></span>)}</div></div><div className="field"><label htmlFor="message">How can we support you?</label><textarea id="message" name="message" rows={7} required/></div><button className="btn btn-primary" type="submit">Send Inquiry</button></form></div></section></Reveal></PageShell>}
