import Link from "next/link";
import { ArrowRight, BarChart3, Building2, ClipboardCheck, Cog, Leaf, Network, Search, Target, TrendingUp } from "lucide-react";

const services=[
[Leaf,"Sustainability & ESG Strategy","Translate priorities and commitments into practical strategies, governance structures, and implementation pathways."],
[Building2,"Climate Impact & Infrastructure Innovation","Measure environmental performance and develop practical climate, resilience, and infrastructure solutions."],
[Target,"Implementation Advisory & Strategic Execution","Bridge the distance between strategy and action through structured roadmaps, ownership, and delivery support."],
[BarChart3,"Data, Reporting & Decision Support","Build dashboards, reporting systems, metrics, and coordination structures that improve visibility and decisions."],
[Cog,"Operational Systems & Process Optimization","Embed sustainability into everyday processes and strengthen operational performance."],
[ClipboardCheck,"Program & Project Management","Deliver sustainability, climate, and transformation initiatives through structured program and project management."]
];
const work=[
["ESG & Sustainability Implementation","Governance structures, reporting frameworks, KPI systems, materiality assessment, and implementation roadmaps."],
["Program, Project & Operational Management","Complex stakeholder coordination, workplans, reporting systems, workflow design, and operational delivery."],
["Climate, Infrastructure & Systems Innovation","AI-enabled infrastructure concepts, climate resilience planning, systems analysis, and operational innovation."],
["Data, Reporting & Decision Support","Performance dashboards, ESG data workflows, indicator systems, reporting templates, and decision-support tools."]
];
export default function Home(){return <>
<section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Sustainability • Implementation • Performance</div><h1>Sustainability solutions that move beyond strategy.</h1><p className="lead">Helping SMEs and Community Development Financial Institutions translate sustainability ambition into practical systems, measurable implementation, and long-term organizational performance.</p><div className="hero-actions"><Link className="btn btn-primary" href="/services">Explore Our Services <ArrowRight size={18}/></Link><Link className="btn btn-secondary" href="/selected-work">View Our Work</Link></div></div><div className="hero-panel"><div className="orbit"><div className="orbit-core">CT</div><span className="node node-1">Governance</span><span className="node node-2">Data</span><span className="node node-3">Delivery</span><span className="node node-4">Impact</span></div></div></div></section>
<section className="section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">What we do</div><h2>Implementation-focused consulting</h2></div><p>We help organizations build the structures, systems, and decision-support capabilities required to convert sustainability ambition into sustained organizational performance.</p></div><div className="grid-3">{services.map(([Icon,title,text])=>{const I=Icon as typeof Leaf;return <article className="card" key={String(title)}><div className="icon-badge"><I size={22}/></div><h3>{String(title)}</h3><p>{String(text)}</p></article>})}</div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Calden Terre Impact Framework</div><h2>From discovery to sustained value</h2></div><p>Our six-stage implementation framework supports organizations from current-state assessment through execution, measurement, optimization, and long-term capability building.</p></div><div className="framework">{[["Discover","Assess current state"],["Strategize","Build the roadmap"],["Implement","Operationalize solutions"],["Measure","Track ESG & climate performance"],["Optimize","Improve systems and processes"],["Sustain","Embed long-term value"]].map((s,i)=><div className="step" key={s[0]}><div className="step-num">{i+1}</div><b>{s[0]}</b><span>{s[1]}</span></div>)}</div></div></section>
<section className="section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Selected Work</div><h2>Evidence of practical execution</h2></div><p>Representative examples of implementation, advisory, and operational work delivered across sustainability, climate, governance, reporting, and organizational performance.</p></div><div className="grid-4">{work.map(([t,d])=><article className="card" key={t}><h3>{t}</h3><p>{d}</p></article>)}</div><div style={{marginTop:30}}><Link className="btn btn-secondary" href="/selected-work">Explore Selected Work</Link></div></div></section>
<section className="section"><div className="container"><div className="grid-3"><div className="card"><div className="icon-badge"><Search size={22}/></div><h3>Implementation-focused</h3><p>We translate ambition into clear ownership, practical workflows, and measurable outcomes.</p></div><div className="card"><div className="icon-badge"><Network size={22}/></div><h3>Systems thinking</h3><p>We integrate sustainability into governance, operations, reporting, and decision-making.</p></div><div className="card"><div className="icon-badge"><TrendingUp size={22}/></div><h3>Long-term value</h3><p>We strengthen internal capabilities that support continuous improvement and lasting performance.</p></div></div></div></section>
</>}
