import Link from "next/link";
import { ArrowRight, BarChart3, Building2, ClipboardCheck, Cog, Leaf, Network, Search, Target, TrendingUp } from "lucide-react";
import Collapsible from "@/components/Collapsible";

import Reveal from "@/components/Reveal";
import ResourceCapture from "@/components/ResourceCapture";
import HeroArt from "@/components/HeroArt";

const services=[
[Leaf,"Sustainability & ESG Strategy","Translate priorities and commitments into practical strategies, governance structures, and implementation pathways."],
[Building2,"Climate Impact & Infrastructure Innovation","Measure environmental performance and develop practical climate, resilience, and infrastructure solutions."],
[Target,"Implementation Advisory & Strategic Execution","Bridge the distance between strategy and action through structured roadmaps, ownership, and delivery support."],
[BarChart3,"Data, Reporting & Decision Support","Build dashboards, reporting systems, metrics, and coordination structures that improve visibility and decisions."],
[Cog,"Operational Systems & Process Optimization","Embed sustainability into everyday processes and strengthen operational performance."],
[ClipboardCheck,"Program & Project Management","Deliver sustainability, climate, and transformation initiatives through structured program and project management."]
];
const work=[
["ESG & Sustainability Implementation","Governance structures, reporting frameworks, KPI systems, materiality assessment, and implementation roadmaps."],
["Program, Project & Operational Management","Complex stakeholder coordination, workplans, reporting systems, workflow design, and operational delivery."],
["Climate, Infrastructure & Systems Innovation","AI-enabled infrastructure concepts, climate resilience planning, systems analysis, and operational innovation."],
["Data, Reporting & Decision Support","Performance dashboards, ESG data workflows, indicator systems, reporting templates, and decision-support tools."]
];
export default function Home(){return <>
<section className="hero"><div className="container hero-grid"><div><div className="eyebrow hero-in-1">Sustainability • Implementation • Performance</div><h1 className="hero-in-2">Sustainability solutions that move beyond strategy.</h1><p className="lead hero-in-3">Helping SMEs and Community Development Financial Institutions translate sustainability ambition into practical systems, measurable implementation, and long-term organizational performance.</p><div className="hero-actions hero-in-4"><Link className="btn btn-primary" href="/services">Explore Our Services <ArrowRight size={18}/></Link><Link className="btn btn-secondary" href="/selected-work">View Our Work</Link></div></div><HeroArt/></div></section>
<Reveal><section className="section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">What we do</div><h2>Implementation-focused consulting</h2></div><p>We help organizations build the structures, systems, and decision-support capabilities required to convert sustainability ambition into sustained organizational performance.</p></div><div className="grid-3">{services.map(([Icon,title,text])=>{const I=Icon as typeof Leaf;return <article className="card" key={String(title)}><div className="icon-badge"><I size={22}/></div><h3>{String(title)}</h3><Collapsible><p>{String(text)}</p></Collapsible></article>})}</div></div></section></Reveal>
<Reveal><section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Calden Terre Impact Framework</div><h2>From discovery to sustained value</h2></div><p>Our six-stage implementation framework supports organizations from current-state assessment through execution, measurement, optimization, and long-term capability building.</p></div><div className="framework">{[["Discover","Assess current state"],["Strategize","Build the roadmap"],["Implement","Operationalize solutions"],["Measure","Track ESG & climate performance"],["Optimize","Improve systems and processes"],["Sustain","Embed long-term value"]].map((s,i)=><div className="step" key={s[0]}><div className="step-num">{i+1}</div><b>{s[0]}</b><span>{s[1]}</span></div>)}</div></div></section></Reveal>
<Reveal><section className="section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Selected Work</div><h2>Evidence of practical execution</h2></div><p>Representative examples of implementation, advisory, and operational work delivered across sustainability, climate, governance, reporting, and organizational performance.</p></div><div className="grid-4">{work.map(([t,d])=><article className="card" key={t}><h3>{t}</h3><Collapsible>{d}</Collapsible></article>)}</div><div style={{marginTop:30}}><Link className="btn btn-secondary" href="/selected-work">Explore Selected Work</Link></div></div></section></Reveal>
<Reveal><section className="section resource-section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Resource</div><h2>Start Here</h2></div><p>A practical first step for turning implementation challenges into clear, achievable action.</p></div><div className="resource-card"><div><span className="resource-badge">20-Page Workbook</span><h3>The Implementation Gap Assessment</h3><p>A practical self-assessment and action guide for SMEs and CDFIs. Includes a full fillable workbook: a gap tracker, a prioritization scorecard, and a 30-day action plan, built around our Implementation Gap methodology.</p></div><ResourceCapture/></div></div></section></Reveal>
<Reveal><section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Why Calden Terre</div><h2>What makes our approach different</h2></div><p>Three things we hold ourselves to on every engagement.</p></div><div className="grid-3"><div className="card"><div className="icon-badge"><Search size={22}/></div><h3>Implementation-focused</h3><Collapsible><p>We translate ambition into clear ownership, practical workflows, and measurable outcomes.</p></Collapsible></div><div className="card"><div className="icon-badge"><Network size={22}/></div><h3>Systems thinking</h3><Collapsible><p>We integrate sustainability into governance, operations, reporting, and decision-making.</p></Collapsible></div><div className="card"><div className="icon-badge"><TrendingUp size={22}/></div><h3>Long-term value</h3><Collapsible><p>We strengthen internal capabilities that support continuous improvement and lasting performance.</p></Collapsible></div></div></div></section></Reveal>
</>}
