import Link from "next/link";
import { ArrowRight, BarChart3, Building2, ClipboardCheck, Cog, Leaf, Network, Target, ShieldCheck } from "lucide-react";
import Collapsible from "@/components/Collapsible";

import Reveal from "@/components/Reveal";
import ResourceCapture from "@/components/ResourceCapture";
import HeroArt from "@/components/HeroArt";

const services=[
[Leaf,"Readiness & Strategy","Assess where sustainability stands today and translate priorities, customer expectations, and market pressure into an achievable roadmap."],
[Target,"Implementation & Execution","Put the roadmap into motion through structured project plans, clear ownership, and coordinated program and project delivery."],
[Cog,"Operational Systems & Process Improvement","Build the everyday workflows, procedures, and accountability structures that make sustainability part of how the business runs."],
[BarChart3,"Measurement & Decision Support","Develop key performance indicators, dashboards, and data collection processes that turn activity into evidence leadership can use."],
[Building2,"Climate Impact & Responsible Sourcing","Track climate and environmental performance and strengthen responsible sourcing and supply chain practices where relevant."],
[ClipboardCheck,"Reporting & Continuous Improvement","Communicate progress credibly and build the internal capability to keep improving year after year."]
];
const work=[
[Leaf,"https://images.pexels.com/photos/7681091/pexels-photo-7681091.jpeg?auto=compress&cs=tinysrgb&w=800","Sustainability Implementation","Governance structures, reporting frameworks, KPI systems, materiality assessment, and implementation roadmaps.","Stronger governance, implementation readiness, and reporting consistency"],
[Network,"https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=800","Program, Project & Operational Management","Complex stakeholder coordination, workplans, reporting systems, workflow design, and operational delivery.","Improved coordination, execution visibility, and delivery discipline"],
[Building2,"https://images.pexels.com/photos/35158337/pexels-photo-35158337.jpeg?auto=compress&cs=tinysrgb&w=800","Climate, Infrastructure & Systems Innovation","AI-enabled infrastructure concepts, climate resilience planning, systems analysis, and operational innovation.","Stronger resilience, systems visibility, and implementation planning"],
[BarChart3,"https://images.pexels.com/photos/577210/pexels-photo-577210.jpeg?auto=compress&cs=tinysrgb&w=800","Data, Reporting & Decision Support","Performance dashboards, sustainability data workflows, indicator systems, reporting templates, and decision-support tools.","Better data quality, performance measurement, and decision support"]
];
export default function Home(){return <>
<section className="hero"><div className="container hero-grid"><div><h1 className="hero-in-2">Sustainability implementation for growing businesses.</h1><p className="lead hero-in-3">Calden Terre is a sustainability implementation consultancy helping established small and growing businesses turn sustainability goals into practical systems, measurable actions and credible progress.</p><div className="eyebrow hero-in-4" style={{fontSize:"clamp(16px,1.8vw,20px)",marginBottom:14}}>Sustainability • Implementation • Credible Progress</div><div className="hero-actions hero-in-4"><Link className="btn btn-primary" href="/contact">Start a Project Conversation <ArrowRight size={18}/></Link><Link className="btn btn-secondary" href="/services">Explore Our Services</Link></div></div><HeroArt/></div></section>
<Reveal><section className="section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">What we do</div><h2>Connected capabilities that turn ambition into practical implementation</h2></div></div><div className="grid-3">{services.map(([Icon,title,text])=>{const I=Icon as typeof Leaf;return <article className="card" key={String(title)}><div className="icon-badge"><I size={22}/></div><h3>{String(title)}</h3><Collapsible><p>{String(text)}</p></Collapsible></article>})}</div></div></section></Reveal>
<Reveal><section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Calden Terre Impact Framework</div><h2>A six-stage framework for closing the implementation gap</h2></div></div><div className="framework">{[["Discover","Understand the business and its gaps"],["Strategize","Set practical priorities and a roadmap"],["Implement","Put agreed systems into operation"],["Measure","Establish KPIs and monitor performance"],["Optimize","Improve systems from the evidence"],["Sustain","Embed accountability and continuous improvement"]].map((s,i)=><div className="step" key={s[0]}><div className="step-num">{i+1}</div><b>{s[0]}</b><span>{s[1]}</span></div>)}</div></div></section></Reveal>
<Reveal><section className="section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Who We Serve</div><h2>Built primarily for established small and growing businesses</h2></div></div><div className="serve-grid"><article className="card"><div className="icon-badge"><Building2 size={22}/></div><h3>Established Small and Growing Businesses</h3><p>Our primary clients. Businesses with active operations and sustainability goals, whether prompted by customers, investors, lenders, or their own values, that need help translating intention into structured action, measurement, and credible communication. We support these businesses across industries, adapting our approach to each organization&apos;s operations, resources, and priorities.</p></article><article className="card"><div className="icon-badge"><Network size={22}/></div><h3>Institutional and Business-Support Partners</h3><p>Community Development Financial Institutions, community lenders, chambers of commerce, business-development programs, and foundations that support small businesses. We partner with these organizations to design and deliver sustainability assessments, workshops, toolkits, and implementation programs for the business cohorts they serve.</p><p style={{marginTop:14}}><Link href="/contact" style={{color:"var(--terracotta)",fontWeight:600,fontSize:13}}>Discuss a Sponsored Business Program →</Link></p></article></div></div></section></Reveal>
<Reveal><section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Selected Work</div><h2>Evidence of practical execution across sustainability, climate, and governance work</h2></div></div><div className="grid-4">{work.map(([Icon,img,t,d])=>{const I=Icon as typeof Leaf;return <article className="card card--media" key={String(t)}><div className="work-card-media"><img src={String(img)} alt="" loading="lazy"/><span className="work-card-badge"><I size={18}/></span></div><div className="card-media-body"><h3>{String(t)}</h3><Collapsible>{String(d)}</Collapsible></div></article>})}</div><div style={{marginTop:30}}><Link className="btn btn-secondary" href="/selected-work">Explore Selected Work</Link></div></div></section></Reveal>
<Reveal><section className="section resource-section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Resource</div><h2>Assess your implementation gap in one practical first step</h2></div></div><div className="resource-card"><div><span className="resource-badge">20-Page Workbook</span><h3>The Implementation Gap Assessment</h3><p>A practical self-assessment for established small and growing businesses ready to move sustainability goals into action. Includes a full fillable workbook: a gap tracker, a prioritization scorecard, and a 30-day action plan, built around our Implementation Gap methodology.</p></div><ResourceCapture/></div></div></section></Reveal>
<section className="statement-band"><div className="container"><div className="eyebrow">Our Thesis</div><blockquote>Sustainability strategies rarely fail from lack of ambition. They fail in the gap between commitment and execution, and closing that gap is the focus of our work.</blockquote></div></section>
<Reveal><section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Why Organizations Choose Calden Terre</div><h2>Four reasons established and growing businesses choose Calden Terre</h2></div></div><div className="grid-4"><div className="card"><div className="icon-badge"><Target size={22}/></div><h3>Implementation-Focused</h3><Collapsible><p>We do not stop at strategy. We build the ownership, workflows, and systems that carry sustainability goals into daily operations.</p></Collapsible></div><div className="card"><div className="icon-badge"><BarChart3 size={22}/></div><h3>Data and Decision Support</h3><Collapsible><p>We turn scattered information into dashboards, KPIs, and reporting that support real decisions, not just paperwork.</p></Collapsible></div><div className="card"><div className="icon-badge"><Cog size={22}/></div><h3>Practical Systems</h3><Collapsible><p>We build systems sized to how your business actually operates, not templates built for a much larger organization.</p></Collapsible></div><div className="card"><div className="icon-badge"><ShieldCheck size={22}/></div><h3>Accountability and Governance</h3><Collapsible><p>We put ownership and review rhythms in place so sustainability progress continues well after our engagement ends.</p></Collapsible></div></div></div></section></Reveal>
</>}
