import Link from "next/link";
import { ArrowRight, BarChart3, Building2, Cog, Leaf, Network, Target, ShieldCheck, Landmark, Banknote, Search, Compass, Rocket, TrendingUp } from "lucide-react";
import Collapsible from "@/components/Collapsible";

import Reveal from "@/components/Reveal";
import ResourceCapture from "@/components/ResourceCapture";
import HeroArt from "@/components/HeroArt";

const services=[
[Search,"Discover","Sustainability Readiness Assessment","Where your sustainability efforts stand today, what your customers, lenders, or investors are asking for, and where to start."],
[Compass,"Strategize","Roadmap & Strategy","Scattered ambition turned into a scoped, sequenced plan sized to what your business can realistically resource."],
[Rocket,"Implement","Implementation & Systems Build","The everyday workflows, procedures, and accountability structures that carry sustainability into daily operations."],
[TrendingUp,"Measure & Optimize","Ongoing Advisory & Accountability","Tracking progress, troubleshooting what isn't working, and keeping momentum in place month over month."],
[ShieldCheck,"Sustain","Credibility & Readiness Support","Responding to lender and customer sustainability requirements, and preparing for certification if you choose to pursue one."]
];
const work=[
[Leaf,"https://images.pexels.com/photos/7681091/pexels-photo-7681091.jpeg?auto=compress&cs=tinysrgb&w=800","ESG & Sustainability Implementation","Governance structures, reporting frameworks, KPI systems, materiality assessment, and implementation roadmaps.","Stronger governance, implementation readiness, and reporting consistency"],
[Network,"https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=800","Program, Project & Operational Management","Complex stakeholder coordination, workplans, reporting systems, workflow design, and operational delivery.","Improved coordination, execution visibility, and delivery discipline"],
[Building2,"https://images.pexels.com/photos/35158337/pexels-photo-35158337.jpeg?auto=compress&cs=tinysrgb&w=800","Climate, Infrastructure & Systems Innovation","AI-enabled infrastructure concepts, climate resilience planning, systems analysis, and operational innovation.","Stronger resilience, systems visibility, and implementation planning"],
[BarChart3,"https://images.pexels.com/photos/577210/pexels-photo-577210.jpeg?auto=compress&cs=tinysrgb&w=800","Data, Reporting & Decision Support","Performance dashboards, ESG data workflows, indicator systems, reporting templates, and decision-support tools.","Better data quality, performance measurement, and decision support"]
];
export default function Home(){return <>
<section className="hero"><div className="container hero-grid"><div><h1 className="hero-in-2">Sustainability solutions that move beyond strategy.</h1><p className="lead hero-in-3">Calden Terre is a sustainability solutions provider that helps organizations, institutions, and growing businesses close the gap between sustainability ambition and practical implementation.</p><div className="eyebrow hero-in-4" style={{fontSize:"clamp(16px,1.8vw,20px)",marginBottom:14}}>Sustainability • Implementation • Performance</div><div className="hero-actions hero-in-4"><Link className="btn btn-primary" href="/services">Explore Our Services <ArrowRight size={18}/></Link><Link className="btn btn-secondary" href="/selected-work">View Our Work</Link></div></div><HeroArt/></div></section>
<Reveal><section className="section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">What we do</div><h2>Five services, one path from ambition to practical implementation</h2></div></div><div className="grid-3">{services.map(([Icon,stage,title,text])=>{const I=Icon as typeof Search;return <article className="card" key={String(title)}><div className="icon-badge"><I size={22}/></div><span style={{display:"block",fontSize:11,fontWeight:700,letterSpacing:".08em",textTransform:"uppercase",color:"var(--terracotta)",marginBottom:8}}>{String(stage)}</span><h3>{String(title)}</h3><Collapsible><p>{String(text)}</p></Collapsible></article>})}</div><p style={{marginTop:30}}><Link href="/framework" style={{color:"var(--terracotta)",fontWeight:600,fontSize:14}}>See the full six-stage Calden Terre Impact Framework →</Link></p></div></section></Reveal>
<Reveal><section id="who-we-serve" className="section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Who We Serve</div><h2>Built for businesses ready to implement, and the partners who support them</h2></div></div><div className="serve-list">{[[Building2,"Established Small and Growing Businesses","Our primary clients, across industries."],[Landmark,"CDFIs and Community Lenders","Sponsored programs for the businesses they finance."],[Network,"Chambers and Business-Support Organizations","Cohort programs for the businesses they serve."],[Banknote,"Banks and Financial Institutions","Direct engagement through Sustainable Lending & Investment Advisory."]].map(([Icon,t,d])=>{const I=Icon as typeof Building2;return <div className="serve-item" key={String(t)}><div className="icon-badge"><I size={20}/></div><h3>{String(t)}</h3><p>{String(d)}</p></div>})}</div><p style={{marginTop:28}}><Link href="/contact" style={{color:"var(--terracotta)",fontWeight:600,fontSize:14}}>Discuss a sponsored business program →</Link></p></div></section></Reveal>
<Reveal><section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Our Work</div><h2>Evidence of practical execution across sustainability, climate, and governance work</h2></div></div><div className="grid-4">{work.map(([Icon,img,t,d])=>{const I=Icon as typeof Leaf;return <article className="card card--media" key={String(t)}><div className="work-card-media"><img src={String(img)} alt="" loading="lazy"/><span className="work-card-badge"><I size={18}/></span></div><div className="card-media-body"><h3>{String(t)}</h3><Collapsible>{String(d)}</Collapsible></div></article>})}</div><div style={{marginTop:30}}><Link className="btn btn-secondary" href="/selected-work">Explore Our Work</Link></div></div></section></Reveal>
<Reveal><section className="section resource-section section-soft"><div className="container"><div className="section-head"><div><div className="eyebrow">Resource</div><h2>Assess your implementation gap in one practical first step</h2></div></div><div className="resource-card"><div><span className="resource-badge">20-Page Workbook</span><h3>The Implementation Gap Assessment</h3><p>A practical self-assessment for established small and growing businesses ready to move sustainability goals into action. Includes a full fillable workbook: a gap tracker, a prioritization scorecard, and a 30-day action plan, built around our Implementation Gap methodology.</p></div><ResourceCapture/></div></div></section></Reveal>
<section className="statement-band"><div className="container"><div className="eyebrow">Our Thesis</div><blockquote>Sustainability strategies rarely fail from lack of ambition. They fail in the gap between commitment and execution, and closing that gap is the focus of our work.</blockquote></div></section>
<Reveal><section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Why Organizations Choose Calden Terre</div><h2>Four reasons established and growing businesses choose Calden Terre</h2></div></div><div className="grid-4"><div className="card"><div className="icon-badge"><Target size={22}/></div><h3>Implementation-Focused</h3><Collapsible><p>We do not stop at strategy. We build the ownership, workflows, and systems that carry sustainability goals into daily operations.</p></Collapsible></div><div className="card"><div className="icon-badge"><BarChart3 size={22}/></div><h3>Data and Decision Support</h3><Collapsible><p>We turn scattered information into dashboards, KPIs, and reporting that support real decisions, not just paperwork.</p></Collapsible></div><div className="card"><div className="icon-badge"><Cog size={22}/></div><h3>Practical Systems</h3><Collapsible><p>We build systems sized to how your business actually operates, not templates built for a much larger organization.</p></Collapsible></div><div className="card"><div className="icon-badge"><ShieldCheck size={22}/></div><h3>Accountability and Governance</h3><Collapsible><p>We put ownership and review rhythms in place so sustainability progress continues well after our engagement ends.</p></Collapsible></div></div></div></section></Reveal>
</>}
